### ISSUE TITLE
Что со сылкой

### ISSUE THREAD

**Issue by danill5** [lukeeey/DiscordRelay#1]
Неработает ссылка https://discord.com/oauth2/authorize?client_id=YOUR-CLIENT-ID-HERE&permissions=11264&scope=bot
Хз может обясить
![Screenshot_2021-04-08-11-43-29-948_com mi globalbrowser](https://user-images.githubusercontent.com/82145363/113996286-b3282600-985f-11eb-8e64-9620ca47bbbd.jpg)

**Comment by lukeeey** [comment]
I don’t speak Russian or whatever that is.

Replace “YOUR-CLIENT-ID-HERE” with the client ID that you found by following the previous steps in the install guide.
